version: "3.7"
services:
  jupyter:
    # image: jupyter/pyspark-notebook:latest
    build: .
    container_name: jupyter_pyspark
    ports:
      - "8887:8888"
    volumes:
      - ./data:/home/jovyan/work
    environment:
      - PYSPARK_PYTHON=python3
      - SPARK_MASTER=local[*]  # Local Spark Master for single-node execution
    command: start-notebook.sh --NotebookApp.token=''
